* refs
** comp
https://github.com/comp-org/comp
** matchups, a baseball model
https://github.com/hdoupe/Matchups
* talking to hank 2019 03 21
** parameters are defined by the defaults file
at the top level
and they couldn't be deduced from the schema file
** the schema file defines one schema
dims defines dims of parameters; optional defines attributes about parameters.
dims determine parameters; optionals don't.
** number_dims
This corresponds to numpy.ndarray.ndim
Here's where it's 0 (this is real):
        "number_dims": 0,
        "value": [
            {"year": 2024, "marital_status": "single", "value": 13673.68},
it's 0 because the inner "value" is only one number.

If instead it was
        "number_dims": 0,
        "value": [
            {"year": 2024, "marital_status": "single"
            , "value": [13673.68,2,3]},
then number_dimns would be 1.
** the required attributes of a parameter
*** are defined here: https://paramtools.readthedocs.io/en/latest/spec.html#parameter-object
*** are these
“param_name”: The name of the parameter as it is used in the modeling project.
“title”: “title”: A human readable name for the parameter.
“description”: Describes the parameter.
“notes”: Additional advice or information.
“type”: Data type of the parameter. See Type property.
“number_dims”: Number of dimensions of the parameter. See Number-Dimensions property
“value”: A list of Value objects.
“validators”: A mapping of Validator objects.
“out_of_range_{min/max/other op}_msg”: Extra information to be used in the message(s) that will be displayed if the parameter value is outside of the specified range. Note that this is in the spec but not currently implemented.
“out_of_range_action”: Action to take when specified parameter is outside of the specified range. Options are “stop” or “warn”. Note that this is in the spec but only “stop” is currently implemented.
** One parameter can depend on another for validation.
       "validators": {
           "range": {
               "min": 0,
               "max": "ii_bracket_2"
           }
       }
   },
   "ii_bracket_2": {
** dimensions are labels for values
No label needed if the value doesn't vary.
*** ii_bracket_1 is a parameter that depends on stuff, defined in "value" under it
*** dimensions are separate from, and determine, parameters
*** value under a parameter is a list of dicts; value under one of those dicts is a function output, where the inputs are tagged by the other keys in the dict
** section_1 in taxparams-demo
groups the parameters into sections
* matchups
** notes
*** defaults
The 'description" and "notes" fields are appended in the UI, in that order, to become the message displayed when you hover over the "info" icon.
** asked, answered
*** why is the number_dims field 1 for batters but 0 for pitchers?
There can be multiple batters.
*** a database of what? apps? baseball stats?
**** answer: don't worry about it
The database is just the postgres database that powers the COMP website. As a model publishing an app with COMP, you shouldn't have to worry about the database.
**** question: more detail
in the README.md and DATABASE.md documents for comp
 https://github.com/comp-org/comp

*** does spelling matter?
**** answer: yes
The reason Matchups asks the user to spell it right is that the list of names is too long for selecting from a dropdown to be convenient.
**** question: more detail
In Matchups/matchups/defaults.json, under the "pitcher" field there appears this note:
"Make sure the name of the pitcher is correct. A good place to reference this is baseball-reference.com"
That is followed by a validator that lists peoples' names. Does the validator obsolete the note?
*** Duplicates are meaningless in a validator
*** The name "compbaseball" is obsolete, replaced by "matchups".
** partially answered, to study
*** meta- vs. model parameters
**** what do they do?
***** answer
the meta parameters are passed to these three things
  the package defaults function
    https://github.com/comp-org/comp/blob/master/docs/ENDPOINTS.md#package-defaults
  the parse user adjustments function
    https://github.com/comp-org/comp/blob/master/docs/ENDPOINTS.md#parse-user-adjustemnts
  the run simulation function
    https://github.com/comp-org/comp/blob/master/docs/ENDPOINTS.md#run-simulation
***** question: more detail
 One should be described in schema.json, the other in defaults.json? But those files seem not to matter; COMP just wants some json returned by the Python interface functions, correct?
 Is the distinction that the meta parameters affect the set of defaults presented to the viewer?
**** where do they come from?
***** matchups uses ParamTools; COMP doesn't need it
ParamTools is what expects schema.json and defaults.json files.
***** question: more detail
In Matchups, I see metaparameters described in schema.json, and model parameters in defaults.json. But that's an immaterial distinction, right? COMP just wants some json returned by the Python interface functions, and doesn't care where that JSON came from, correct?
*** can I run a duplicate of COMP?
**** partial answer
The install instructions allow you to run a local instance of comp. It'll be served locally at http://127.0.0.1:8000/. You are welcome to spin up a local instance of COMP and see how things look. A few of my friends have been able to get it running locally with minimal help. So, it can be done, but it's definitely not required. You can just fill out the publishing template, I'll plug everything in for you, and I'll push it to a demo server for your review.
**** question, detail
Does the "install instructions" section of the COMP readme indicate how to actually serve a webpage like https://www.compmodels.com/? (I can't imagine what else it would do, but I don't want to go through the work of installing it before knowing I'm doing it.)
** unsure whether to send
*** should I send python code to execute the docker container
* ParamTools
** questions
*** The schema for schemas
Does every element of "dims" require a "type" and a "validators", and does every element of "optional" require a "type" and a "number_dims"? And are no other level-3 fields permissible in either position?
*** can the shape of the (fixed-dimension) output value grid of a parameter vary across input vectors?
*** optional dimensions can have dimension zero?
 e.g. from the the example at
     https://paramtools.readthedocs.io/en/latest/spec.html#specification-schema
 there's
     "section_3": {"type": "str", "number_dims": 0},
*** what is array_first?
And why is it both global to the Parameters class (#1 below) and local to a particular instance of Parameters (#2 below)?

class Parameters:
    ...
    array_first = False # 1

    def __init__( self, initial_state=None ... # 2

*** how can a schema (e.g. behresp) have no dimensions, yet default values?
*** what are parameter attributes
They appear to be distinct from parameter values -- c.f. the definition of specification() in ParamTools/paramtools/parameters.py
